name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    # Do not ignore bash profile files. From:
    defaults:
      run:
        shell: bash -l {0}
        
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up toolchain
      run: echo "/scratch/tk/chipyard/.conda-env/riscv-tools/bin/" >> $GITHUB_PATH
    - name: Make
      run: make
