name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Do not ignore bash profile files. From:
    defaults:
      run:
        shell: bash -l {0}
        
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up toolchain
      run: |
        wget https://github.com/ucb-bar/RISC-V-GNU-Toolchain-Prebuilt/releases/download/v2023.12.30/riscv64-unknown-toolchain.tar.xz
        tar -xf riscv64-unknown-toolchain.tar.xz
    - name: Make default
      run: |
        export PATH="$GITHUB_WORKSPACE/riscv64-unknown-toolchain/bin/:$PATH"
        make clean
        make
    - name: Make bearlyml
      run: |
        export PATH="$GITHUB_WORKSPACE/riscv64-unknown-toolchain/bin/:$PATH"
        make clean
        make TARGET=./examples/chipyard-tests/hello/
        # spike build/hello.elf
    - name: Make fe310
      run: |
        export PATH="$GITHUB_WORKSPACE/riscv64-unknown-toolchain/bin/:$PATH"
        make clean
        make CHIP=fe310